name: Push to CodeCommit

on:
  push:
    branches:
      - develop

jobs:
  push-to-codecommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          # Ensure the SSH directory exists
          mkdir -p ~/.ssh
          
          # Remove previous known hosts and SSH key if they exist
          rm -f ~/.ssh/known_hosts
          rm -f ~/.ssh/id_rsa
          
          # Write the new SSH key from GitHub Secrets and set appropriate permissions
          echo "${{ secrets.INTEGRATIONS_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Configure SSH for AWS CodeCommit using wildcard for all regions
          echo -e "Host git-codecommit.*.amazonaws.com\n  User APKA2VOAKXIYP452PU2U\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no" > ~/.ssh/config
          
          # Add CodeCommit's host key to known_hosts to bypass verification
          ssh-keyscan -H git-codecommit.us-east-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: Verify SSH Connection
        run: |
          # Test the SSH connection to AWS CodeCommit
          ssh -T git-codecommit.us-east-1.amazonaws.com || echo "SSH connection failed"

      - name: Fetch latest remote changes
        run: |
          # Fetch the latest changes from the remote repository
          git fetch origin

      - name: Force push from develop to main (or master)
        run: |
          # Make sure we are on the correct branch
          git checkout develop

          # Ensure the develop branch is up to date with remote
          git pull origin develop --rebase

          # Check if 'master' or 'main' exists in the remote repo
          git branch -r

          # Push from develop to main (or master)
          # git push -f ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/instance-5b9262be5134773d05c99f2a-container_im-e1d13317f1cb78acd717ca3a develop:master
          git push -f ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/instance-67988eff1ce3eec00cafae7a-container_im-b98a779a1063821a401a457a refactor-wip:master